[package]
name = "webowie-proxmox-client"
version = "0.1.1"
description = "webOwie Infrastructure Control Plane for Proxmox VE"
authors = ["webOwie"]
edition = "2021"

[lib]
name = "webowie_proxmox_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
url = "2"
